[package]
name = "ytrs"
version = "0.1.4"
authors = ["Owlyat"]
edition = "2024"
rust-version = "1.88"
include = [
  "src/**/*",
  "Cargo.toml",
  "README.md",
  "LICENSE",
]
license = "GPL-3.0"
homepage = "https://github.com/Owlyat/ytrs"
description = "A crossplatform Youtube TUI to download/watch/listen videos/music/transcript using MPV/YT-DLP/ffmpeg/Rustypipe"
repository = "https://github.com/Owlyat/ytrs"
keywords = [
  "tui",
  "youtube",
  "terminal",
]

[dependencies]
anyhow = "1.0"
ratatui = "0.30.2"
rustypipe = "0.11"
serde_json = "1.0"
tokio = { version = "1.52", features = ["full"] }
yt-dlp = "2.8.3"
ratatui-image = { version = "11.0.8", features = ["crossterm", "image-defaults"], default-features = false }
reqwest = "0.13.4"
image = "0.25.10"
ratatui-macros = "0.7.0"
strum = { version = "0.28", features = ["derive"] }
chrono = "0.4"
terminal-clipboard = "0.4"
thiserror = "2.0"
ollama-rs = { version = "0.3", features = ["stream"] }
tokio-stream = "0.1"
serde = "1.0"
tokio-util = "0.7"
clap = { version = "4.6", features = ["derive"] }
lofty = "0.24"
midir = "0.11"
ratatui-textarea = "0.9.1"
ratatui-explorer = "0.3.0"
tracing = { version = "0.1.44", features = ["release_max_level_debug"] }
tracing-appender = "0.2.5"
tracing-subscriber = "0.3.23"
toml = "1.1.4"
